Importing all essential libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re
import warnings
warnings.filterwarnings('ignore')

In [2]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

Storing the csv into a variable using pandas.

In [ ]:
df=pd.read_csv('IMDB Dataset.csv')
#https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews?resource=download

Checking the data's information and structure.

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

Creating a function to clean the data i.e. removing all unnecessary elements that might interfere with the prediction.

In [8]:
def cleaning(text):
    text=text.lower()
    text=re.sub(r'<.*?>','',text)
    text=re.sub(r'[^a-zA-Z\s]','',text)
    tokens=word_tokenize(text)
    stop_words=set(stopwords.words('english'))
    tokens=[token for token in tokens if token not in stop_words]
    return ' '.join(tokens)

Calling the cleaning function to create a new column of cleaned review for using as a better parameter.

In [9]:
df['cleaned_review'] = df['review'].apply(cleaning)

In [10]:
df.head()

,review,sentiment,cleaned_review
0,One of the other reviewers has mentioned that ...,positive,one reviewers mentioned watching oz episode yo...
1,A wonderful little production. <br /><br />The...,positive,wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,negative,basically theres family little boy jake thinks...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love time money visually stunni...

Extracting feature using tfid Vectorization.

In [11]:
tfidf = TfidfVectorizer(max_features=5000)

Converting text to tdif features.

In [12]:
x=tfidf.fit_transform(df['cleaned_review'])
y=df['sentiment'].map({'positive':1, 'negative':0})

Setting up the variables for model to train.

In [13]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [15]:
print(X_train.shape,y_train.shape)

(40000, 5000) (40000,)

Choosing a model: here we are choosing logisticRegression.

In [16]:
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

Finally predicting. after training the model.

In [17]:
y_pred=model.predict(X_test)

Checking the matrixes.

In [18]:
acc=accuracy_score(y_test,y_pred)
prec=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)

In [20]:
print('Model prediction accuracy: ',acc*100,'%')
print('Model prediction precision: ',prec*100,'%')
print('Model prediction recall: ',recall*100,'%')

Model prediction accuracy:  88.68 %
Model prediction precision:  87.80723824269401 %
Model prediction recall:  90.03770589402659 %

How will i approach in order to improve the model?
1. we can choose different better algorthms like Random Forest, XGBoost.
2. we can add more feature like sentiment score.
3. we can use more data.

Automating the process for tesing on sample input.

In [21]:
def predict(text):
    text2=cleaning(text)
    para=tfidf.transform([text2])
    prediction=model.predict(para)
    return 'postive' if prediction[0]==1 else 'negative'

Testing on sample input.

In [ ]:
reviews = [
    "This movie was okay to watch but could have been better.",
    "I was unsure about this movie but it was a really good watch.",
]
for i in reviews:
    print(f"\nReview: ",i)
    print(f"Predicted Sentiment: ",predict(i))

Review:  This movie was okay to watch but could have been better.
Predicted Sentiment:  negative

Review:  I was unsure about this movie but it was a really good watch.
Predicted Sentiment:  postive